### ISSUE TITLE
Add a provider to install a global requirement

### ISSUE THREAD

**Issue by daften** [djoos-cookbooks/composer#51]
E.g. phpcs, phpcpd.
Now each of these repositories has the same code, the same template, ...
What I'd propose is a provider which uses the composer_project provider in the background with :require as action, so the composer.json file in a folder is manipulated instead of begin remade. It would also create a symlink from the global install dir (e.g. /usr/local/bin), which would be an attribute in this cookbook.

The advantages are:
- all composer stuff could easily be installed in e.g. /usr/local. If you want to install specific items somewhere else, it can easily be adapted.
- No more replication of code across cookbooks

The provider would e.g. be
composer_install_global 'install_dir' do
  package 'package_name'
  version 'version'
  path 'path'
end

What do you think? I'll start working on a PR for this later.

**Comment by daften** [comment]
Any feedback on this? :)

**Comment by djoos** [comment]
Hi @daften,

sorry for not getting back to you any sooner. I definitely like the idea; do send me over a PR so we can get the ball rolling...

Thanks in advance!

Kind regards,
David

**Comment by daften** [comment]
No problem, can be busy :)
Done in #53 ;)

**Comment by matejvelikonja** [comment]
:+1:  for the global install
