### ISSUE TITLE
Composer installs to /usr/bin/composer, but the cookbook queries /usr/local/bin/composer

### ISSUE THREAD

**Issue by metaa** [djoos-cookbooks/composer#76]
My current hotfix is to run `ln -s /usr/bin/composer /usr/local/bin/composer` after the installation of composer, but in my opinion that should better be fixed.

**Comment by daften** [comment]
How come it installs to /usr/bin/composer for you, it should install to /usr/local/bin/composer as per https://github.com/djoos-cookbooks/composer/blob/master/recipes/install.rb

**Comment by metaa** [comment]
I'm not really sure about why that happens.
My OS is Debian 9 (stretch) and running inside a VirtualBox VM with the newest versions of Chef & co.

**Comment by metaa** [comment]
Well ... aparently I installed composer from outside the cookbook in another place and just forgot about that one.
