### ISSUE TITLE
Fatal error: Allowed memory size of 1073741824 bytes exhausted

### ISSUE THREAD

**Issue by steven-cherry** [djoos-cookbooks/composer#78]
Hi,

When running composer_project update on a project its running out of memory, see the extract below. Is there a parameter I can pass which ups the default memory allocation?

[0m* composer_project[/u/current] action update
  * execute[update-composer-for-project] action run
    [0m
    ================================================================================[0m
    [31mError executing action `run` on resource 'execute[update-composer-for-project]'[0m
    ================================================================================[0m
    
[0m    Mixlib::ShellOut::ShellCommandFailed[0m
    ------------------------------------[0m
    Expected process to exit with [0], but received '255'
[0m    ---- Begin output of /usr/local/bin/composer update --no-interaction --no-ansi  --no-dev    ----
[0m    STDOUT: Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 72 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Decisions.php on line 40

**Comment by daften** [comment]
memory allocation is defined by the PHP runtime, not by composer. You'll need to edit the php.ini file for the php executable that composer uses. We usually set this to -1 so it has unlimited power. See also https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors

**Comment by steven-cherry** [comment]
Thanks daften
